AllCops:
  TargetRubyVersion: 2.7

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: False

Layout/EndOfLine:
  Enabled: False

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false
